로지스틱 회귀

In [1]:
import pandas as pd
fish=pd.read_csv('https://bit.ly/fish_csv_data')
fish.head()#데이터 불러오기

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [2]:
print(pd.unique(fish['Species']))#생선의 종류 출력

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']


In [7]:
fish_input=fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
print(fish_input[:5])
fish_target=fish['Species'].to_numpy()#타깃값과 인풋값 설정

[[242.      25.4     30.      11.52     4.02  ]
 [290.      26.3     31.2     12.48     4.3056]
 [340.      26.5     31.1     12.3778   4.6961]
 [363.      29.      33.5     12.73     4.4555]
 [430.      29.      34.      12.444    5.134 ]]


In [8]:
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target=train_test_split(fish_input,fish_target,random_state=42)
#데이터 나누기

In [10]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(train_input)
train_scaled=ss.transform(train_input)
test_scaled=ss.transform(test_input)
#데이터 표준점수로 전처리

이중분류

In [11]:
bream_smelt_indexes=(train_target=='Bream')|(train_target=='Smelt')
train_bream_smelt=train_scaled[bream_smelt_indexes]
target_bream_smelt=train_target[bream_smelt_indexes]
#도미와 빙어의 데이터만 골라냄

In [13]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(train_bream_smelt,target_bream_smelt)
print(lr.predict(train_bream_smelt[:5]))
print(lr.predict_proba(train_bream_smelt[:5]))
#로지스틱 회귀 학습및 예측값 출력과 각각에 대한 확률 출력

['Bream' 'Smelt' 'Bream' 'Bream' 'Bream']
[[0.99759855 0.00240145]
 [0.02735183 0.97264817]
 [0.99486072 0.00513928]
 [0.98584202 0.01415798]
 [0.99767269 0.00232731]]


In [15]:
print(lr.coef_,lr.intercept_)#가중치 값 확인

[[-0.4037798  -0.57620209 -0.66280298 -1.01290277 -0.73168947]] [-2.16155132]


다중분류

In [17]:
lr=LogisticRegression(C=20,max_iter=1000)#규제값 반복횟수 설정
lr.fit(train_scaled,train_target)
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.9327731092436975
0.925


In [18]:
print(lr.coef_,lr.intercept_)#가중치 값 출력

[[-1.49002452 -1.02914945  2.59347296  7.70356699 -1.20069497]
 [ 0.19618491 -2.01065841 -3.77978758  6.50490995 -1.99483965]
 [ 3.56279371  6.34358541 -8.48971882 -5.75757024  3.79307922]
 [-0.10458094  3.60318549  3.93067688 -3.61734746 -1.75069885]
 [-1.40060817 -6.07504028  5.25968854 -0.87221028  1.86043575]
 [-1.38526764  1.49215536  1.39226949 -5.67733599 -4.40096958]
 [ 0.62150265 -2.32407812 -0.90660147  1.71598703  3.69368809]] [-0.09205092 -0.26290886  3.2510131  -0.14743222  2.65497661 -6.78781882
  1.38422111]
