In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
wine=pd.read_csv('https://bit.ly/wine_csv_data')
data=wine[['alcohol','sugar','pH']].to_numpy()
target=wine['class'].to_numpy() #데이터 넘파이 배열로 바꾸기
train_input,test_iput,train_target,test_target=train_test_split(data,target,test_size=0.2,random_state=42)
#데이터준비 이젠 설명하기도 지겹다

In [5]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_jobs=-1,random_state=42,warm_start=True)
scores=cross_validate(rf,train_input,train_target,return_train_score=True,n_jobs=-1)
print(scores)
#랜덤포레스트로 학습및 교차 검증

{'fit_time': array([0.2390542 , 0.23605347, 0.2350533 , 0.23505354, 0.23705387]), 'score_time': array([0.02500606, 0.02500653, 0.02400517, 0.02700663, 0.02400613]), 'test_score': array([0.88461538, 0.88942308, 0.90279115, 0.88931665, 0.88642926]), 'train_score': array([0.9971133 , 0.99663219, 0.9978355 , 0.9973545 , 0.9978355 ])}


In [6]:
rf.fit(train_input,train_target)
print(rf.feature_importances_)#모델 학습 후

[0.23167441 0.50039841 0.26792718]


In [29]:
print(rf.oob_score_())#잉여 데이터를 이용하여 점수 출력

AttributeError: 'RandomForestClassifier' object has no attribute 'oob_score_'

엑스트라 트리

In [31]:
from sklearn.ensemble import ExtraTreesClassifier
et=ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores=cross_validate(et,train_input,train_target,n_jobs=-1,return_train_score=True)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))
#엑스트라 트리 분류모델 학습

0.9974503966084433 0.8887848893166506


In [32]:
et.fit(train_input,train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


그레이디언트 부스팅

In [33]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier(random_state=42)
scores=cross_validate(gb,train_input,train_target,return_train_score=True,n_jobs=-1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))
#그레이디언트 부스팅 분류모델 학습 밑 교차검증

0.8881086892152563 0.8720430147331015


In [34]:
gb=GradientBoostingClassifier(random_state=42,n_estimators=500,learning_rate=0.2)
scores=cross_validate(gb,train_input,train_target,return_train_score=True,n_jobs=-1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))
#학습률과 트리개수를 100->500으로 0.1->0.2로 조정함

0.9464595437171814 0.8780082549788999


In [37]:
gb.fit(train_input,train_target)
print(gb.feature_importances_)

[0.15872278 0.68011572 0.16116151]


히스토그램 기반 그레이디언트 부스팅

In [38]:
from sklearn.ensemble import  HistGradientBoostingClassifier
hgb=HistGradientBoostingClassifier(random_state=42)
scores=cross_validate(hgb,train_input,train_target,return_train_score=True)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))
#히스토그램 기반 그레이디언트 부스팅으로 학습

0.9321723946453317 0.8801241948619236


In [39]:
hgb.fit(train_input,train_target)
print(hgb.score(test_iput,test_target))

0.8723076923076923
